#!/usr/bin/python
#
# Copyright 2014 Marco Ceppi <marco@ceppi.net>
#
# juju-pprint is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# juju-pprint is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# For a full copy of the GNU General Public License, see
# <http://www.gnu.org/licenses/>.

import sys

from utils import get_units, print_unit


def main():
    quiet = False
    # I heard they invented this cool thing called argparse
    if '--description' in sys.argv:
        print "Collapsed, pretty version of juju status"
        sys.exit()

    if '--help' in sys.argv:
        print "Collapsed, pretty version of juju stats"
        sys.exit()

    if '-q' in sys.argv:
        quiet = True

    for unit in get_units():
        if not unit.subordinate:
            print_unit(unit, quiet=quiet)
        else:
            print_unit(unit, 2, quiet=quiet)


if __name__ == "__main__":
    main()
