#!/bin/bash

if [ "$1" == "--description" ]; then
    echo "Rsync any local changes on unit to a directory"
    exit 0
fi

if [ "$1" == "--help" ]; then
    echo "usage: juju sync-charm UNIT [DIR]"
    echo "  UNIT  Juju unit with local changes to charm"
    echo "  DIR   Directory to rsync changes to. Default: ."
    exit 0
fi


if [ "$1" == "-y" ]; then
    FORCE=yes
    shift
fi


if [ -z "$1" ]
then
    echo "You must provide a unit name" >&2
    exit 1
fi

UNIT=$1
DIR=${2:-.}
shift
shift

if [ -z "$FORCE" ]; then
    echo "WARNING: This will attempt to merge local changes to the charm on $UNIT into $DIR"
    read -p "Continue? [y/N] " doit
    if [ "${doit,,}" != "y" ]
    then
        exit 1
    fi
fi

UNITDIR="unit-$(echo $UNIT | sed 's#/#-#')"
REMOTE_DIR="/var/lib/juju/agents/$UNITDIR/charm/"

rsync -Wa --exclude revision --exclude .juju-charm "$@" -e "juju ssh --pty=false $UNIT" :$REMOTE_DIR $DIR
